init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

environment:
  MIN_FREE_GIGABYTES: 25

test_script:
  - sh: df -h
  - sh: df -k | awk '/^\/dev/{print $1 $4}'
  - sh: |
      MIN_FREE_KILOBYTES=$(expr $MIN_FREE_GIGABYTES \* 1024 \* 1024)
      for VAL in $(df -k | awk '/ \/$/{print $4}'); do
          if [ $VAL -lt $MIN_FREE_KILOBYTES ]; then
              echo "Free space: $VAL KB is less than $MIN_FREE_GIGABYTES"
              exit 2
          else
              echo "Free space: $VAL KB is more than $MIN_FREE_GIGABYTES"
          fi
      done

build: off
