init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

environment:
  MIN_FREE_MEGABYTES: 15360

test_script:
  - sh: df -h
  - sh: |
      echo "Disk usage in Megabytes:"
      df -B 1M | awk '/^\/dev/{print $1 $4}'
  - sh: |
      for VAL in $(df -B 1M | awk '/ \/$/{print $4}'); do
          if [ $VAL -lt $MIN_FREE_MEGABYTES ]; then
              echo "Free space: $VAL MB is less than $MIN_FREE_MEGABYTES MB"
              exit 2
          else
              echo "Free space: $VAL MB is more than $MIN_FREE_MEGABYTES MB"
          fi
      done

build: off
